spring:
  application:
    name: tourism-back
  profiles:
    include:
      - env
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${server.host}:3306/tourism?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: ${mysql.password}
  redis:
    host: ${server.host}
    port: 6379
    password: ${redis.password}
    database: 0
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

server:
  port: 8080

mybatis-plus:
  mapper-locations: classpath*:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

app:
  jwt:
    secret: ${jwt.secret}
    expire-seconds: 86400

logging:
  level:
    com.af.tourism: INFO
